name: Build Native Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/spring-native-app:latest .
          docker push ${{ secrets.ACR_REGISTRY }}/spring-native-app:latest